### ISSUE TITLE
effort/current controller hardware interface

### ISSUE THREAD

**Issue by indraneelpatil** [RIVeR-Lab/epos_hardware#25]
Dear community,
I am trying to set up a Maxon EC90 motor and an EPOS2 motor controller to work with ros_control.
I have an effort controller implemented in ros_control and now I need a hardware interface to relay the torque commands to the motor via the EPOS2 controller!

Accordingly to the documentation, the EPOS2 controller has an additional current profile mode which can be used to implement controlled torque on the motor shaft.

As per my knowledge (which is fairly limited) epos_hardware ros package can only be used with the position profile mode and the velocity profile mode. I would like to request whosoever reads this post to guide me on how I should proceed with implementing a hardware interface for the effort controller mode for my EPOS controller.

Any form of help would be greatly appreciated!
Warm Regards,
Indraneel.

**Comment by JimmyDaSilva** [comment]
@indraneelpatil Not sure I understand what you didn't succeed to achieve, but here is an example of me setting up an `effort_controller` with `ros_control` and running the current profile on `epos_hardware`

Epos hardware configuration in the yaml:
https://github.com/kuka-isir/lwr_peg_in_hole/blob/master/launch/screwdriver.yaml

URDF to declare the EffortJointInterface:
https://github.com/kuka-isir/lwr_peg_in_hole/blob/master/launch/screwdriver.urdf#L19-L27

The launch file to start it all:
https://github.com/kuka-isir/lwr_peg_in_hole/blob/master/launch/screwdriver.launch

**Comment by indraneelpatil** [comment]
@JimmyDaSilva Thank you so much for replying! I have been trying this for days!
I followed exactly your instructions and implemented the three files (urdf, launch and parameter file):
My parameter file (after inserting serial number and specifications according to my datasheet) looks like this : 

```
# Time in seconds
# Current in amps
# position, velocity, and acceleration in device units
my_joint_actuator:
  actuator_name: 'test_joint_actuator'
  serial_number: '0x602079025628'
  operation_mode: 'current'
  clear_faults: true
  torque_constant: 70.5

  motor:
    type: 10
    ec_motor:
      nominal_current: 6.06
      max_output_current: 10.000
      thermal_time_constant: 234
      number_of_pole_pairs: 12

  sensor:
    type: 1
    incremental_encoder:
      resolution: 2048
      inverted_polarity: false

 # safety:
 #   max_following_error: 20000
 #   max_profile_velocity: 800
 #   max_acceleration: 10000

  #position_profile:
   # velocity: 100
    #acceleration: 80
    #deceleration: 35

  #velocity_profile:
  #  acceleration: 10000
  #  deceleration: 2000

```
But when I run the launch file, I get this error :
[ERROR] [1530115774.657967792]: current is not a valid operation mode

Any suggestions? Thank you so much again!
